# Generated by Django 4.2.10 on 2024-02-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='city',
            field=models.CharField(default='gg', max_length=255),
            preserve_default=False,
        ),
    ]
