# Generated by Django 4.2.10 on 2024-02-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_founder_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
