# Generated by Django 4.2.10 on 2024-02-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0005_employee_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='pitch_deck_document',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
